### ISSUE TITLE
Bug: Keys on mapped elements

### ISSUE THREAD

**Issue by paulrichan** [capriok/Pepiti-Stats#17]
### Provide environment information

pnpm run dev

### Describe the bug

Warning: Each child in a list should have a unique "key" prop.

### Link to reproduction

no :)

### To reproduce

run the dev server

**Comment by capriok** [comment]
who what when why where

**Comment by paulrichan** [comment]
> who what when why where

it was saying in the navbar and some other places but i'm not seeing it today

**Comment by paulrichan** [comment]
![image](https://github.com/capriok/Pepiti-Stats/assets/75490402/cfcd509d-c46f-43f8-809b-8b712cbde198)
