### ISSUE TITLE
API: /rider/report

### ISSUE THREAD

**Issue by capriok** [capriok/Pepiti-Stats#19]
### Describe the where the feature lives

API: /rider/report

### Describe the User Story

As a developer i want to have more information returned from the endpoint to fulfill the needs for admin report review process. 

- add `date`, when report was submitted, (is this the id sliced?)
- add `race` object with race information (so the client doesnt have to fetch a race for each report)
- add `by` object (user that submitted report)
- change `proofs: string` to `proofs: string[]` to support multiple links to proof. (client will allow max 3 for now)

### Describe the steps toward the solution you see

- [ ] Do python guru things

**Comment by agalera** [comment]
valid post:
```json
{
    "race_id": "63d3cdc706bc08738be863e9",
    "guid": "FF01100001013A65F0",
    "by": "FF01100001013A65F0",
    "reason": "test",
    "proofs": ["https://economipedia.com/wp-content/uploads/test-de-estr%C3%A9s.png", "pep.hehe", "example"]
}
```
proofs is always a array

GET /api/v1/rider/report
GET /api/v1/rider/report/<status(open|closed)>
example: https://pepiti.com/stats/api/v1/rider/report
maybe in the future it should just return a smaller list, and have another endpoint with more detail

DELETE /api/v1/rider/report/<report_id>
changes to closed state, do we need more state types?

**Comment by capriok** [comment]
no i think open and closed is good for now, this is solid
